title: Planty
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
favicon: images/violet-chestnut.png
logo_dark: images/LOGO-LOS-CACHORROS-BLANCO.png
logo_light: images/marvelous-mahogany.png
hamburger_background_image: images/noun_Dog_3587160-4.png
bg_image_primary: images/photo-1583511655826-05700d52f4d9.jpg
bg_image_primary_opacity: 60
bg_image_secondary: images/caring-tortoise.png
bg_image_product: images/pink-mango.png
snipcart_api_key: ''
palette: yellow
main_menu:
  - title: CATÁLOGO
    url: /store
    style: link
  - title: SOBRE NOSOTROS
    url: /about
    style: link
  - title: INFORMACIÓN
    url: /faq
    style: link
sass:
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
domain: 'https://modern-sycamore-7fe64.netlify.app'
footer_text: POWER BY SERVIVOMX
